Algoritmo "Divisão"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicitar dois números inteiros, faz a divisão e exibi o resultado
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
   numero1: real
   numero2: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um número: ")
   Leia(numero1)
   Escreva("Digite outro número: ")
   Leia(numero2)
   resultado <- numero1 / numero2
   Escreva("O resultado da divisão deu: ", resultado)

Fimalgoritmo