Algoritmo "Laco_de_repeticao_parar"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Carlos dos Santos
// Descrição   : Exemplo de um laço de repetição parar, onde Contador que é
// zero, vai de 1 até o 10 exibindo um por um
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 17/04/2026
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Laço de repetição Parar")
   escreval("")
   para contador de 1 até 10 passo 1 faça
      escreval(contador)
   fimpara
Fimalgoritmo