Algoritmo "metros_para_centimetro"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costas dos Santos
// Descrição   : Leia um valor em metros e converta para centímetros.
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
   valor: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número em metros para ser convertido em centimetro: ")
   leia(valor)
   resultado <- valor *100
   escreva("A conversão é: ", resultado, "cm")

Fimalgoritmo