Algoritmo "perimetro_quadrado"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Carlos dos Santos 
// Descrição   : Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 28/03/2026
Var
// Seção de Declarações das variáveis 
  lado: inteiro
  resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o lado do quadrado e descubra o perímetro dele: ")
   leia(lado)
   resultado <- lado * 4
   escreva("Esse é o perímetro: ", resultado, "cm")

Fimalgoritmo