Algoritmo "Soma"
// Disciplina  : [Lógica de programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Vai solicitar dois números inteiros, somar e exibir o resultado
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
   numero1: inteiro
   numero2: inteiro
   resultado: inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Conta de mais: +
   Escreva("Digite um número:")
   Leia(numero1)
   Escreva("Digite outro número:")
   Leia(numero2)
   resultado <- numero1 + numero2
   Escreva("A soma do resultado é: ",resultado)
   
Fimalgoritmo