Algoritmo "sucessor"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costas dos Santos
// Descrição   : Solicitar um número para o usuario, e exibir o sucessor
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   numero: inteiro
   sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(numero)
   sucessor <- numero + 1
   escreva("Este é o sucessor do número ", numero, ": ", sucessor)

Fimalgoritmo