Algoritmo "troca_de_valores"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Carlos dos Santos
// Descrição   : Leia dois valores armazenados nas variáveis A e B. Troque os
// valores entre elas.
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 28/03/2026
Var
// Seção de Declarações das variáveis
   a: inteiro
   b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o primeiro valor: ")
   leia(a)
   escreva("Digite o segundo valor: ")
   leia(b)
   escreval(" ")
   escreval("Novo valor do primeiro: ", b)
   escreval("Novo valor do segundo: ", a)

Fimalgoritmo