Algoritmo "troque_tres_valores"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Carlos dos Santos
// Descrição   : Leia três valores (inteiro, reais e caracteres) para A, B e C,
// e troque os valores entre eles, fazendo B exibir o valor do A.
// Autor(a)    : Julia dos Santos Fernandes
// Data atual  : 04/04/2026
Var
   // Seção de Declarações das variáveis
   valor1: real
   valor2: inteiro
   valor3: caracter

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Escreva um número inteiro: ")
   leia(valor1)
   escreva("Escreva um número real: ")
   leia(valor2)
   escreva("Escreva um nome: ")
   leia(valor3)
   escreval("Seu número inreiro é ", valor3, " o real é ", valor2, " o nome é ", valor3, " Certo?")

Fimalgoritmo